import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ReduxProvider } from "@/store/ReduxProvider";


export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <ReduxProvider>
         {children}
        <Toaster/>
       </ReduxProvider>
      </body>
    </html>
  );
}
